/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

/**
 *
 * @author Ethan
 */
public class Ingresar_Editar_Retirar extends javax.swing.JFrame {

    Aviso objAviso = new Aviso(this);

    public Ingresar_Editar_Retirar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Ingresos = new javax.swing.JPanel();
        lblBienvenida4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInstruccionesIngreso = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstIngresoPaq = new javax.swing.JList<>();
        lblPaqueteIngreso = new javax.swing.JLabel();
        cbPaqueteIngreso = new javax.swing.JComboBox<>();
        lblCuantosPaquetesIngreso = new javax.swing.JLabel();
        spnCantPaq = new javax.swing.JSpinner();
        lblConfirmacionIngreso = new javax.swing.JLabel();
        cbConfirmacionIngreso = new javax.swing.JCheckBox();
        btnIngresoInventario = new javax.swing.JButton();
        btnFinalizarPedido = new javax.swing.JButton();
        Edicion = new javax.swing.JPanel();
        lblBienvenidaIngreso = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInstruccionesIngreso1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstpaqEdit = new javax.swing.JList<>();
        lblPaqueteEdit = new javax.swing.JLabel();
        cbPaquetesEdit = new javax.swing.JComboBox<>();
        lblCuantosPaquetesEdit = new javax.swing.JLabel();
        spnCantEdit = new javax.swing.JSpinner();
        lblConfirmacionEdit = new javax.swing.JLabel();
        cbEdit = new javax.swing.JCheckBox();
        btnFinalizarPedido1 = new javax.swing.JButton();
        Retiros = new javax.swing.JPanel();
        lblBienvenidaRetirar = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtInstruccionesRetiro = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstRetiroPaq = new javax.swing.JList<>();
        lblPaqueteRetiro = new javax.swing.JLabel();
        cbPaqueteRetiro = new javax.swing.JComboBox<>();
        lblCuantosPaquetesRetiro = new javax.swing.JLabel();
        spnCantPaqRet = new javax.swing.JSpinner();
        lblConfirmacionRetiro = new javax.swing.JLabel();
        cbConfirmacionRetiro = new javax.swing.JCheckBox();
        btnFinalizarPedido2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenida4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBienvenida4.setText("Sistema de inventarios: Modo ingreso de paquetes");

        txtInstruccionesIngreso.setEditable(false);
        txtInstruccionesIngreso.setColumns(20);
        txtInstruccionesIngreso.setLineWrap(true);
        txtInstruccionesIngreso.setRows(5);
        txtInstruccionesIngreso.setText("Instrucciones para el ingreso de paquetes: \n1. Debe indicar el tipo de paquete a ingresar (Se enlistan algunos).\n2. Seleccione la unidades a ingresar.\n3. Confirme su seleccion.\n4. Clic en el botón \"Ingresar\".");
        txtInstruccionesIngreso.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtInstruccionesIngreso);

        lstIngresoPaq.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Paquete básico", "Paquete avanzado", "Paquete avanzado+", "Paquete premium" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstIngresoPaq.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstIngresoPaqValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstIngresoPaq);

        lblPaqueteIngreso.setText("¿Qué paquete deseas agregar?");

        cbPaqueteIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paquete básico", "Paquete avanzado", "Paquete avanzado+", "Paquete premium" }));
        cbPaqueteIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaqueteIngresoActionPerformed(evt);
            }
        });

        lblCuantosPaquetesIngreso.setText("¿Cuántos paqutes deseas agregar?");

        lblConfirmacionIngreso.setText("Confirme la orden");

        cbConfirmacionIngreso.setText("Confirmo que esta correcto");
        cbConfirmacionIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConfirmacionIngresoActionPerformed(evt);
            }
        });

        btnIngresoInventario.setText("Salir");
        btnIngresoInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoInventarioActionPerformed(evt);
            }
        });

        btnFinalizarPedido.setText("Finalizar");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IngresosLayout = new javax.swing.GroupLayout(Ingresos);
        Ingresos.setLayout(IngresosLayout);
        IngresosLayout.setHorizontalGroup(
            IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresoInventario)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresosLayout.createSequentialGroup()
                .addGap(0, 124, Short.MAX_VALUE)
                .addGroup(IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenida4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(IngresosLayout.createSequentialGroup()
                        .addGroup(IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCuantosPaquetesIngreso)
                            .addComponent(lblConfirmacionIngreso)
                            .addComponent(lblPaqueteIngreso))
                        .addGap(18, 18, 18)
                        .addGroup(IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCantPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbConfirmacionIngreso)
                            .addComponent(cbPaqueteIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        IngresosLayout.setVerticalGroup(
            IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaqueteIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaqueteIngreso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuantosPaquetesIngreso)
                    .addComponent(spnCantPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbConfirmacionIngreso)
                    .addComponent(lblConfirmacionIngreso))
                .addGap(18, 18, 18)
                .addGroup(IngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresoInventario)
                    .addComponent(btnFinalizarPedido))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Ingresos", Ingresos);

        lblBienvenidaIngreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBienvenidaIngreso.setText("Sistema de inventarios: Modo edición de paquetes");

        txtInstruccionesIngreso1.setEditable(false);
        txtInstruccionesIngreso1.setColumns(20);
        txtInstruccionesIngreso1.setLineWrap(true);
        txtInstruccionesIngreso1.setRows(5);
        txtInstruccionesIngreso1.setText("Instrucciones para la edición/corrección de paquetes: \n1. Debe indicar el tipo de paquete a editar (Se enlistan la existencia).\n2. Seleccione la unidades a corregir.\n3. Confirme su selección.\n4. Clic en el botón \"Editar\".");
        txtInstruccionesIngreso1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtInstruccionesIngreso1);

        lstpaqEdit.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Paquete básico", "Paquete avanzado", "Paquete avanzado+", "Paquete premium" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lstpaqEdit);

        lblPaqueteEdit.setText("¿Qué paquete deseas editar?");

        cbPaquetesEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paquete básico", "Paquete avanzado", "Paquete avanzado+", "Paquete premium" }));
        cbPaquetesEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaquetesEditActionPerformed(evt);
            }
        });

        lblCuantosPaquetesEdit.setText("¿Cuántos paqutes son?");

        spnCantEdit.setModel(new javax.swing.SpinnerNumberModel(1, null, 5, 1));

        lblConfirmacionEdit.setText("Confirme la orden");

        cbEdit.setText("Confirmo que esta correcto");
        cbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditActionPerformed(evt);
            }
        });

        btnFinalizarPedido1.setText("Finalizar");
        btnFinalizarPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedido1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EdicionLayout = new javax.swing.GroupLayout(Edicion);
        Edicion.setLayout(EdicionLayout);
        EdicionLayout.setHorizontalGroup(
            EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EdicionLayout.createSequentialGroup()
                .addGap(0, 128, Short.MAX_VALUE)
                .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EdicionLayout.createSequentialGroup()
                        .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCuantosPaquetesEdit)
                            .addComponent(lblConfirmacionEdit)
                            .addComponent(lblPaqueteEdit))
                        .addGap(18, 18, 18)
                        .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCantEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEdit)
                            .addComponent(cbPaquetesEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(EdicionLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblBienvenidaIngreso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EdicionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarPedido1)
                .addGap(142, 142, 142))
        );
        EdicionLayout.setVerticalGroup(
            EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EdicionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenidaIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaquetesEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaqueteEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuantosPaquetesEdit)
                    .addComponent(spnCantEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEdit)
                    .addComponent(lblConfirmacionEdit))
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarPedido1)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Edición", Edicion);

        lblBienvenidaRetirar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBienvenidaRetirar.setText("Sistema de inventarios: Modo retiro de paquetes");

        txtInstruccionesRetiro.setEditable(false);
        txtInstruccionesRetiro.setColumns(20);
        txtInstruccionesRetiro.setLineWrap(true);
        txtInstruccionesRetiro.setRows(5);
        txtInstruccionesRetiro.setText("Instrucciones para el retiro de paquetes: \n1. Debe indicar el tipo de paquete a retirar (Se enlistan algunos).\n2. Seleccione la unidades a retirar.\n3. Confirme su seleccion.\n4. Clic en el botón \"Retirar\".");
        txtInstruccionesRetiro.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtInstruccionesRetiro);

        lstRetiroPaq.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Paquete básico", "Paquete avanzado", "Paquete avanzado+", "Paquete premium" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(lstRetiroPaq);

        lblPaqueteRetiro.setText("¿Qué paquete deseas retirar");

        cbPaqueteRetiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paquete básico", "Paquete avanzado", "Paquete avanzado+", "Paquete premium" }));

        lblCuantosPaquetesRetiro.setText("¿Cuántos paqutes deseas retirar?");

        lblConfirmacionRetiro.setText("Confirme la orden");

        cbConfirmacionRetiro.setText("Confirmo que esta correcto");
        cbConfirmacionRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConfirmacionRetiroActionPerformed(evt);
            }
        });

        btnFinalizarPedido2.setText("Finalizar");
        btnFinalizarPedido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedido2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RetirosLayout = new javax.swing.GroupLayout(Retiros);
        Retiros.setLayout(RetirosLayout);
        RetirosLayout.setHorizontalGroup(
            RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RetirosLayout.createSequentialGroup()
                .addGap(0, 128, Short.MAX_VALUE)
                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RetirosLayout.createSequentialGroup()
                        .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCuantosPaquetesRetiro)
                            .addComponent(lblConfirmacionRetiro)
                            .addComponent(lblPaqueteRetiro))
                        .addGap(18, 18, 18)
                        .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCantPaqRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbConfirmacionRetiro)
                            .addComponent(cbPaqueteRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
            .addGroup(RetirosLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblBienvenidaRetirar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RetirosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarPedido2)
                .addGap(142, 142, 142))
        );
        RetirosLayout.setVerticalGroup(
            RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetirosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenidaRetirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaqueteRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaqueteRetiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuantosPaquetesRetiro)
                    .addComponent(spnCantPaqRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbConfirmacionRetiro)
                    .addComponent(lblConfirmacionRetiro))
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarPedido2)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Retiros", Retiros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbConfirmacionIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConfirmacionIngresoActionPerformed
        System.out.println("Selecciono la confirmación");
    }//GEN-LAST:event_cbConfirmacionIngresoActionPerformed

    private void cbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditActionPerformed
        //Checkbox de Edicion

    }//GEN-LAST:event_cbEditActionPerformed

    private void cbConfirmacionRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConfirmacionRetiroActionPerformed

    }//GEN-LAST:event_cbConfirmacionRetiroActionPerformed

    private void btnIngresoInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoInventarioActionPerformed
        objAviso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngresoInventarioActionPerformed

    private void cbPaqueteIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaqueteIngresoActionPerformed
       
    }//GEN-LAST:event_cbPaqueteIngresoActionPerformed

    private void btnFinalizarPedido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedido2ActionPerformed
        // boton finalizar retirar paquetes
    }//GEN-LAST:event_btnFinalizarPedido2ActionPerformed

    private void btnFinalizarPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedido1ActionPerformed
        // boton editar paquetes
         System.out.println("Termino el inventario");
    }//GEN-LAST:event_btnFinalizarPedido1ActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        // boton ingresar paquetes
        System.out.println("Termino el inventario");
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void lstIngresoPaqValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstIngresoPaqValueChanged
        if (!evt.getValueIsAdjusting()) {
            Object selectedItem = lstIngresoPaq.getSelectedValue();
            if (selectedItem != null) {
                String selectedItemText = selectedItem.toString();
                System.out.println("Texto seleccionado: " + selectedItemText);

            }
        }
    }//GEN-LAST:event_lstIngresoPaqValueChanged

    private void cbPaquetesEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaquetesEditActionPerformed
        System.out.println("Se activo el Checkbox");
    }//GEN-LAST:event_cbPaquetesEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Editar_Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Editar_Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Editar_Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Editar_Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_Editar_Retirar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Edicion;
    private javax.swing.JPanel Ingresos;
    private javax.swing.JPanel Retiros;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnFinalizarPedido1;
    private javax.swing.JButton btnFinalizarPedido2;
    private javax.swing.JButton btnIngresoInventario;
    private javax.swing.JCheckBox cbConfirmacionIngreso;
    private javax.swing.JCheckBox cbConfirmacionRetiro;
    private javax.swing.JCheckBox cbEdit;
    private javax.swing.JComboBox<String> cbPaqueteIngreso;
    private javax.swing.JComboBox<String> cbPaqueteRetiro;
    private javax.swing.JComboBox<String> cbPaquetesEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBienvenida4;
    private javax.swing.JLabel lblBienvenidaIngreso;
    private javax.swing.JLabel lblBienvenidaRetirar;
    private javax.swing.JLabel lblConfirmacionEdit;
    private javax.swing.JLabel lblConfirmacionIngreso;
    private javax.swing.JLabel lblConfirmacionRetiro;
    private javax.swing.JLabel lblCuantosPaquetesEdit;
    private javax.swing.JLabel lblCuantosPaquetesIngreso;
    private javax.swing.JLabel lblCuantosPaquetesRetiro;
    private javax.swing.JLabel lblPaqueteEdit;
    private javax.swing.JLabel lblPaqueteIngreso;
    private javax.swing.JLabel lblPaqueteRetiro;
    private javax.swing.JList<String> lstIngresoPaq;
    private javax.swing.JList<String> lstRetiroPaq;
    private javax.swing.JList<String> lstpaqEdit;
    private javax.swing.JSpinner spnCantEdit;
    private javax.swing.JSpinner spnCantPaq;
    private javax.swing.JSpinner spnCantPaqRet;
    private javax.swing.JTextArea txtInstruccionesIngreso;
    private javax.swing.JTextArea txtInstruccionesIngreso1;
    private javax.swing.JTextArea txtInstruccionesRetiro;
    // End of variables declaration//GEN-END:variables
}
